### PR TITLE
Add server restart timer

### PR DESCRIPTION
**Pull request by BurstingF**
This should add an optional restart timer based on a suggestion I saw in the discord suggestions channel.

### CODE REVIEW

**Comment by HeyZeer0** [comment]
I think we can find a better place to put this on instead of creating a new overlay. Btw you don't need to add an option to disable it since you can simply hide the entire overlay ^^

**Comment by BurstingF** [comment]
I removed the config option to disable it based on what you said. 
The implementation of this restart timer is based on the already existing stopwatch overlay. I guess I could try to group all those timers in one overlay instead, however, that would make you lose the ability to have different timers in different locations.

**Comment by BurstingF** [comment]
@HeyZeer0 is this perhaps more in the direction you were looking for?

**Comment by BurstingF** [comment]
Closing due to no responses.

**Pull request closed without merging**
