### PR TITLE
better conflict check system

### PR DESCRIPTION
**Pull request by Moire9**
sorry for two commits - i'm not home, so i had to do it via the web UI. you could just do the entire PR as a single commit and squash em. I am extremely confident that this will work, but I have not tested it because I'm not at home. someone else can test it, or the merge can be held off until I am able to test it.

### CODE REVIEW

**Comment by magicus** [comment]
@SirNapkin1334 What problem is this patch supposed to solve?

**Comment by Incompleteusern** [comment]
I think there were 2 commits before but now there's only 1?

**Comment by Moire9** [comment]
yeah i merged them. i've been trying to test it but i've been getting a bunch of errors setting up the enviornment, i've been trying to resolve them

**Comment by HighCrit** [comment]
If you need help setting up the dev environment, join our discord and explain the issues your having.

**Pull request closed without merging**
