### PR TITLE
fix: Fixed chat crash bug

### PR DESCRIPTION
**Pull request by ENORMOUZ**
Fixed a bug when trying to delete chat lines
I lost 50stx to this bug :(

### CODE REVIEW

**Comment by magicus** [comment]
Ooh, that is such sadness! But how did this bug cause you to lose emeralds? 🤔

**Comment by ENORMOUZ** [comment]
Crashed game while transferring items, which caused the item to drop and despawn :(

**Comment by magicus** [comment]
Oh. :( I am sorry.

**Comment by ENORMOUZ** [comment]
Hi 🙏 can this pr be merged so I can stop getting notifications that my Wynntils is outdated, thanks.

**Review by ryanzhoudev — APPROVED** [review]
Kind of not good catching all exception but it's legacy...

**Review by DevScyu — APPROVED** [review]

**Comment by ENORMOUZ** [comment]
Can this be merged?

**Pull request merged**
