### PR TITLE
Fixes a StringIndexOutOfBounds exception

### PR DESCRIPTION
**Pull request by byBackfish**
When putting a crafted item into the skill point gui, and that item has the same name as one of the checked items (like `Daily Rewards`), and then does not have the lore that Wynntils is parsing for, it will crash

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Why not check if one of the indexes are incorrect later?

```java
            } else if (name.contains("Daily Rewards")) { //Daily Reward Multiplier
                int start = lore.indexOf("Streak Multiplier: ") + 19;
                int end = lore.indexOf("Log in everyday to");
                value = Integer.parseInt(lore.substring(start, end));
```

**Comment by kristofbolyai** [comment]
start (and end) will be -1 there

**Comment by byBackfish** [comment]
> start (and end) will be -1 there

well, crafted items could still be used for other items like `Damage Info`, this makes it so every check skips crafted items

**Comment by kristofbolyai** [comment]
So we just skip crafted items and ignore that our parsing logic is pretty much broken?
I would rather put everything in a try-catch then (even though this is still bad)..

**Comment by byBackfish** [comment]
Well yea, it's not the best to just ignore it, but checking if the index is -1 could also have problems then as you can change the lore of a crafted item. You could still give it to someone and then crash them as a "troll". And all those issues are caused by crafted items. Best would probably be to check for -1 and then check make a new method that safely parses the int and returns 0 if its not actually containing an int

**Review by kristofbolyai — APPROVED** [review]
Fine by me.

**Review by ryanzhoudev — APPROVED** [review]

**Pull request merged**
