### PR TITLE
Add next soul point command

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Command is /nextsoulpoints

Lists all servers that are about to give soul points within the next 10 minutes, calculated by server uptimes.

### CODE REVIEW

**Comment by Incompleteusern** [comment]
Try calling `ServerListManager#updateServers` before and seeing if that fixes the need for the offset

**Comment by magicus** [comment]
Interesting idea. Do you think it would be possible to enhance this to provide an easy way to find servers with a suitable uptime for loot runs?

**Comment by magicus** [comment]
> 



> Do you think it would be possible to enhance this to provide an easy way to find servers with a suitable uptime for loot runs?

I've been thinking a bit more about this. I think it would be great to have a `/servers` command, that lists all servers, with uptime, number of free slots and time to next sp. (I think we used to have something like this?)

Then you could all an argument, like `[all] | sp | lootrun`, so that if you specify `sp`, you got the behavior that you've implemented here, sorting and filtering the list wrt time to next soul point. And if you specify `lootrun`, you filter and sort servers based on how suitable they are for lootrun (not too young, but not likely to reboot soon either). And `all` is just the default behavior. (Can maybe be skipped)

I realize this is quite different from your original patch. If you don't think this is a good idea, or think it is but don't want to implement it yourself, just ignore what I've said. :-)

**Comment by ryanzhoudev** [comment]
I think the `/servers` command is a great idea, and the implementation idea you have is really clean too. However, I don't think I can implement this anytime soon, as I'm getting pretty busy with university applications. I'd be happy to hand this PR over to someone else if they would like to give it a shot.

**Comment by magicus** [comment]
I might be able to spend time on it, at least later in december, unless someone else picks it up before that.

**Comment by P0keDev** [comment]
> > 
> 
> 
> 
> > Do you think it would be possible to enhance this to provide an easy way to find servers with a suitable uptime for loot runs?
> 
> I've been thinking a bit more about this. I think it would be great to have a `/servers` command, that lists all servers, with uptime, number of free slots and time to next sp. (I think we used to have something like this?)
> 
> Then you could all an argument, like `[all] | sp | lootrun`, so that if you specify `sp`, you got the behavior that you've implemented here, sorting and filtering the list wrt time to next soul point. And if you specify `lootrun`, you filter and sort servers based on how suitable they are for lootrun (not too young, but not likely to reboot soon either). And `all` is just the default behavior. (Can maybe be skipped)
> 
> I realize this is quite different from your original patch. If you don't think this is a good idea, or think it is but don't want to implement it yourself, just ignore what I've said. :-)

Regarding sorting servers by lootrun quality: It wouldn't really work, since the main aspect of finding a good world to lootrun is for it to not have been looted by someone else recently. Beyond the world not being brand new, uptime isn't a particularly important factor of chest loot.

**Comment by magicus** [comment]
@P0keDev Things might have changed since I studied the theory behind loot runs, but I learned that loot chests basically start out empty, and that the server add loots to them over time, until they are full. And the process to completely fill up the chests take >= 3 hours. Of course, if someone has looted the chests already you're out of luck, but starting your run in a too young world is also bit of pointless.

I've been doing a lot of loot runs lately, and I've started disliking the feature that Wynncraft skips the hub and just throws you into a world. Since I can't tell how old it is, I must start by going back to the hub. Then I might return to the same world, but I needed to know that it was not brand new.

Anyway, listing servers with uptime from a command while on a world seems like a good idea to me, regardless.

**Comment by xcfrg** [comment]
> I've been doing a lot of loot runs lately, and I've started disliking the feature that Wynncraft skips the hub and just throws you into a world. Since I can't tell how old it is, I must start by going back to the hub. Then I might return to the same world, but I needed to know that it was not brand new.

Can't you check the Day counter in the F3 menu? Although I'm not arguing with the uptime command, it's a great idea

**Comment by magicus** [comment]
@xcfrg Interesting idea, I have not even thought about it. That also means that if Wynntils want to check uptime for the current server, we can do so using Minecraft internals, and need not consult the Athena API.

**Comment by ryanzhoudev** [comment]
> I've been doing a lot of loot runs lately, and I've started disliking the feature that Wynncraft skips the hub and just throws you into a world. Since I can't tell how old it is, I must start by going back to the hub. Then I might return to the same world, but I needed to know that it was not brand new.

#382, though that method does take data from the Athena cache

**Comment by magicus** [comment]
@DonkeyBlaster Oh, sorry I missed that. Merged now.

**Comment by ryanzhoudev** [comment]
> Try calling `ServerListManager#updateServers` before and seeing if that fixes the need for the offset

Tried, doesn't work.

**Comment by ryanzhoudev** [comment]
>I've been thinking a bit more about this. I think it would be great to have a /servers command, that lists all servers, with uptime, number of free slots and time to next sp. (I think we used to have something like this?)

I just realized we already have a server command, `/s`. Argument `list` just lists all the servers online, nothing special. Argument `info <server>` just lists the player in that server.

Wynncraft also uses `/server` for some internal thing, and `/servers` just brings you to hub. I think a rework of the `/s` command is the best option here.

**Comment by Incompleteusern** [comment]
Try changing the first - to a + in `ServerProfile#matchTime` and see if that works

**Comment by ryanzhoudev** [comment]
Someone can either take over or we can just let this die; I don't want to work on it rn

**Pull request closed without merging**
