### PR TITLE
Remove unused imports and organise the rest.

### PR DESCRIPTION
**Pull request by TrigonometricDev**
Removed all of the unused imports.

### CODE REVIEW

**Comment by Incompleteusern** [comment]
Im slightly afraid that merging this would cause merge conflicts

**Comment by magicus** [comment]
I recommend against merging this.

We have followed some kind of order for imports, if not very well specified. There's no need to change that.

**Comment by Incompleteusern** [comment]
Also, this is just me, but its kind of fun to remove the excess imports when opening a file

**Comment by P0keDev** [comment]
I'm inclined to agree with magicus; doesn't seem like a particularly productive PR to merge.

**Pull request closed without merging**
