### PR TITLE
feat: Export favorites and waypoints from main menu

### PR DESCRIPTION
**Pull request by ShadowCat117**

### CODE REVIEW

**Review by magicus — DISMISSED** [review]
Good thinking!

**Comment by ShadowCat117** [comment]
> Good thinking!

I will say before this gets merged, not sure if you've seen the discussion on discord but some think this might be too intrusive as this screen always appears. I do agree but it is meant to be a constant reminder that 1.12 will be unsupported soon and it crashes a few seconds into logging in to the server anyway due to the territory changes

**Comment by magicus** [comment]
We said that we would try to keep Legacy crash-free even if it means removing functionality. Can we chop off the territory things that are crashing?

(And yes, I think it can be intrusive)

**Comment by ShadowCat117** [comment]
Tried fixing the territory crash but something else seems to still be casing a crash, sometimes before I can even load into the server so if we want to solve that might have to be done by someone who's more familiar with legacy..

**Comment by Rafii2198** [comment]
I just realized two small issues that originated in my idea, so it is not anything with your implementation. 
* Saying "Artemis (1.20.2)" is not future-proof, if we update to for example 1.20.3 or 1.21 that statement will be false as well as sounds like Artemis is something else completely to Wynntils while it is just a code name. 
   * I suggest changing it to something like just `Wynntils Artemis` or `Wynntils for modern versions of Minecraft`
* Linking to whatever is the latest file on Modrinth could make the user think it is only for one specific loader, the one that happens to be uploaded the latest.
   * Simply changing the link to https://modrinth.com/mod/wynntils for the description or https://modrinth.com/mod/wynntils/versions to all versions should not cause any confusions

**Review by ryanzhoudev — APPROVED** [review]

**Review by kristofbolyai — APPROVED** [review]

**Pull request merged**
