### PR TITLE
Fix NPE crash when chatLine is null

### PR DESCRIPTION
**Pull request by RainVaporeon**
Fix issue #545 after testing for days, implemented a null check in case of NullPointerExceptions

### CODE REVIEW

**Comment by kristofbolyai** [comment]
I dont think this fixes the root cause, chatline get's to be null in some other place.

**Comment by ryanzhoudev** [comment]
I have never actually experienced issue 545. You claim it is an incompatibility with other mods that send messages. What mods are these? Can you rewrite steps to reproduce with more detail so we can determine if this is an issue that needs to be fixed, and if this fix actually works? As far as I know, "[picking up] a large quantity of items constantly" doesn't actually send any messages in chat, so I'm not sure how a chat crash is related to that.

**Comment by RainVaporeon** [comment]
> I have never actually experienced issue 545. You claim it is an incompatibility with other mods that send messages. What mods are these? Can you rewrite steps to reproduce with more detail so we can determine if this is an issue that needs to be fixed, and if this fix actually works? As far as I know, "[picking up] a large quantity of items constantly" doesn't actually send any messages in chat, so I'm not sure how a chat crash is related to that.

Not sure, even without the mods I still crash while grinding mobs (specifically when I was doing squids), another person also told me that they were getting kicked/crashing while just doing /switch to servers, and this patched it apparently

(Not sure if this matters but when picking up ings there are pouch messages? Might be related i dunno)

**Comment by ryanzhoudev** [comment]
The pouch messages when picking up ings are titles/subtitles and those are redirected to the update ticker, so chat shouldn't be involved at all. I have experienced the kick/crash when /switching, but that was only this morning when dxp was announced, so I thought it was just due to server load. I'll pay attention to if it happens during normal server loads

**Review by kristofbolyai — APPROVED** [review]
I guess this is okay as a temporary fix to patch the crashes.

**Review by ryanzhoudev — APPROVED** [review]

**Comment by RainVaporeon** [comment]
Yeah, when I got time I'll look deeper into this, for now this is just a
bandage. Feel free to reject though

2022年7月23日(土) 21:11 Kristof Kovacs ***@***.***>:

**Pull request merged**
