### PR TITLE
Added hotkey for waypoint creating

### PR DESCRIPTION
**Pull request by hohserg1**
It will be more convenient

### CODE REVIEW

**Review by HeyZeer0 — CHANGES_REQUESTED** [review]
The provided key C has conflicts with the third quick spell key

**Comment by hohserg1** [comment]
Ok, key binding moved to [B]

**Comment by hohserg1** [comment]
Ok, conflicts are resolved

**Comment by hohserg1** [comment]
Travis failed on setupDecompWorkspace, I dont understand...

**Comment by hohserg1** [comment]
Ok, conflicts fixed again

**Review by HighCrit — CHANGES_REQUESTED** [review]
mapKey is being reassigned on line 50

**Comment by douira** [comment]
Does this do anything other than just open the waypoint screen? Wouldn't this be easily fixed by creating another `KeyHolder` for this new key binding?
Edit: I've fixed the issue in a separate PR.

**Pull request closed without merging**
