### PR TITLE
its 2022.

### PR DESCRIPTION
**Pull request by TrigonometricDev**
Update copywrite to 2022.

### CODE REVIEW

**Comment by Incompleteusern** [comment]
Do you happen to know why the png and ogg files are changed?

**Comment by tristianthedeveloper** [comment]
> Do you happen to know why the png and ogg files are changed?

Oh.. what in the... I'll look into that and then re-open the PR.

**Comment by TrigonometricDev** [comment]
There we go. That should fix it.

**Comment by TrigonometricDev** [comment]
P.S: Sorry that took so long...

**Comment by Incompleteusern** [comment]
Cool!

**Pull request merged**
