### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by douira**
I've translated the English language file to German. Even though I'm a German native speaker, somebody might want to check through it once before merging just to make sure I've captured the meaning of every phrase correctly.

### CODE REVIEW

**Comment by HighCrit** [comment]
The only thing I noticed is a quote inconsistency in line 47. However, we don't have any German speakers lined up to confirm your translation.

**Comment by douira** [comment]
I fixed the quote inconsistency. Whether or not you want to check my work before merging is up to you. I'm sufficiently confident it's correct with few exceptions, which can be fixed.

**Comment by Quadrum1** [comment]
I can take a look at it

**Comment by Quadrum1** [comment]
So I went trough it and found these errors

> Line 65 / gross -> groß
> Line 76 / Minimapnsymbole -> Minimapsymbole
> Line 112 / haven -> haben
> Line 188 / Gesundheit anderer Spieler
> Line 301 / Manaanleiste -> Manaleiste
> Line 302 / Manaanleiste -> Manaleiste
> Line 303 / Manaanleiste -> Manaleiste
> Line 327 / Resource Pack -> Ressourcen-Paket

**Comment by douira** [comment]
I made a bunch of improvements based on your suggestions and other things I found.

**Comment by douira** [comment]
Why was this closed @HeyZeer0?

**Comment by HeyZeer0** [comment]
> Why was this closed @HeyZeer0?

Whoever was leading the translation branch seems to have abandoned the idea. Can be reopened if someone wish to ^^

**Comment by douira** [comment]
Ah ok so i18n was generally dropped?

**Pull request closed without merging**
