### PR TITLE
PlayerClassProfile: Remove fields from deserializer that is not in the Wynn API anymore

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Review by ryanzhoudev — APPROVED** [review]

**Comment by magicus** [comment]
Do we think it's coming back, or should we search and remove all usages of chestsFound? (Or is it not worth it to keep Legacy clean?)

**Comment by kristofbolyai** [comment]
> Do we think it's coming back, or should we search and remove all usages of chestsFound? (Or is it not worth it to keep Legacy clean?)

I think most of this class is not used, it's just deserialized along with the useful stuff. (iirc I checked and chestcount was not used anywhere)

**Comment by magicus** [comment]
Then maybe just remove it instead of commenting it out..?

**Comment by kristofbolyai** [comment]
> Then maybe just remove it instead of commenting it out..?

Every other unused field is left there, not sure what the original intention was, but I don't think it's worth the time messing with it.

**Comment by magicus** [comment]
Ah, ok then.

**Review by magicus — APPROVED** [review]

**Pull request merged**
