### PR TITLE
Add github workflow caching

### PR DESCRIPTION
**Pull request by xcfrg**
- improves ci build times significantly

### CODE REVIEW

**Comment by magicus** [comment]
Can you explain this patch a bit? You are renaming the workflow file, changing the labels, and adding a cache attribute to the java action..?

**Comment by xcfrg** [comment]
oops, i pushed the wrong commit D:

**Comment by xcfrg** [comment]
I switched adopt to termiun because adoptopenjdk has moved to eclipse termiun (adoptium.net), removed the chmod because in gradle 7 the file is executable by default, and the caching attribute caches the generated source by forgegradle, so it doesn't decompile the game every time it runs

**Review by magicus — CHANGES_REQUESTED** [review]
There is no newline on the last line. But there is a trailing space. Please fix.

**Review by magicus — APPROVED** [review]
I think this looks good. As long as the workflow runs fine...

**Review by DevScyu — APPROVED** [review]

**Pull request merged**
