### PR TITLE
Quest book list page

### PR DESCRIPTION
**Pull request by Incompleteusern**
- Made it so the scale of the map in LootRunPage is no longer a config and depends on player scroll
- Created a Quest book list page class, and had dialogue page, quests page, discovery page, item page, and lootrun page extend it, imo makes the pages more internally consistent
- Changed the layout of the MainPage so it's easier to know there's a second page, pretty sure some people don't even know it exists
  image

- Implemented a shadow for the DialoguePage, could be made configurable
  image

### CODE REVIEW

**Comment by Incompleteusern** [comment]
Should be final commit

**Review by magicus — APPROVED** [review]
Looks like a good cleanup.

**Comment by HeyZeer0** [comment]
Sorry for the delay, I think we should try to find a better solution to the background color rather than just adding a block box 🤔, have you tried shadows?

**Comment by Incompleteusern** [comment]
As in the shadows on the quest/discovery pages?

**Comment by HeyZeer0** [comment]
> As in the shadows on the quest/discovery pages?

No I mean shadows on the text you're writing into the page!

**Comment by Incompleteusern** [comment]
image
Like this?

**Comment by HeyZeer0** [comment]
> image
> Like this?


This looks better, what about the other shadow type? 🤔 
(also I definitely didn't edited your message instead of quoting it)

**Comment by Incompleteusern** [comment]
image

**Comment by Incompleteusern** [comment]
Last commit implemented the following

- Changed the layout of the MainPage so it's easier to know there's a second page, pretty sure some people don't even know it exists
  image

- Implemented the first shadow layout, could be made configurable
  image

**Pull request merged**
