### PR TITLE
Reduced amount of slots in custom player info

### PR DESCRIPTION
**Pull request by BurstingF**
Removed the last row of the custom player info texture as well as adjusted the corresponding x, y values. This row could be removed because it wouldn't contain any values anyway, since we effectively had 21 slots for each column instead of the original 20 slots wynncraft uses.

### CODE REVIEW

**Comment by HeyZeer0** [comment]
Can you take a screenshot of the final result? ^^ @BurstingF

**Comment by BurstingF** [comment]
What exactly do you want a screenshot of? GitHub already provides a nice rich difference between changes in images like this:
firefox_pHVgku6x0f
If it's an in-game screenshot you want then you'll have to wait for a bit till the person who helped me test this comes back.

**Comment by HeyZeer0** [comment]
Mhm, it needs to be in game, so I can verify the alignments =P

**Comment by theniels17** [comment]
This is an ingame screenshot from a server with 20+ players

**Pull request merged**
