### PR TITLE
Ingredient pouch tooltip stacks items + fixed %pouch%, %pouch_free% and %pouch_slots% for ironman classes

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixed %pouch%, %pouch_free% and %pouch_slots% for ironman classes as they didn't account for additional lines on pouch. 

EDIT: This PR also contains code such that ingredient pouch tooltip stacks items, originally from #406. As I derped, that branch got messed up, but in the end, code from #406 should be merged simultaneously with this code, as they depend on each other.

### CODE REVIEW

**Comment by magicus** [comment]
There's a new feature I've missed. What is "ironman"?

**Comment by magicus** [comment]
I think this looks okay but would like to have a review from someone with more knowledge about the ingredient parsing code, and ironman functionality.

**Comment by kristofbolyai** [comment]
> There's a new feature I've missed. What is "ironman"?

Ironman is a challange mode (added in 1.18 iirc). It limits a class, not allowing them to interact with any other player or class, disabling guild bank, ender chest (personal bank), trading, trade market. It also changes the ingredient pouch, allowing them to put any items in there, not only ingredients.

**Comment by kristofbolyai** [comment]
> I think this looks okay but would like to have a review from someone with more knowledge about the ingredient parsing code, and ironman functionality.

Parsing code assumed there is 4 lines before the ingredients, but if the player is ironman, it can be either 5 or 6 lines, making it so it doesn't work with those classes. New parser finds the first item/ingredient line, then parses all other lines, as they are guaranteed to be ingreidents/items.

**Review by magicus — APPROVED** [review]

**Pull request merged**
